server:
  port: 8081

spring:
  name: temporaling
  data:
    mongodb:
      uri: mongodb://admin:admin!pass@192.168.1.3:27018/temporaling?replicaSet=rs0&retryWrites=true
  temporal:
    namespace: default
    connection:
      target: 127.0.0.1:7233
#    workers:
#      - name: send-email-worker
#        task-queue: EMAIL_WORKFLOW_TASK_QUEUE
#    workersAutoDiscovery:
#      packages:
#        - com.adrianojlt.temporaling.workflows
#        - com.adrianojlt.temporaling.activities
